version: '3.8'

services:
  fire-calls-analysis:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../data:/app/data       
      - ../scripts:/app/scripts 
      - ../notebooks:/app/notebooks  
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    ports:
      - "8888:8888"  # upyter Notebook port
    command: >
      bash -c "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
